name: test

on: [push]

permissions: read-all

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      redis:
        image: redislabs/redisearch:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: testpassword

    steps:
      - name: code
        uses: actions/checkout@v4

      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: test
        env:
          REDIS_ADDR: localhost:6379
          REDIS_PASSWORD: testpassword
        run: |
          go get -v -t -d ./...
          go test -cover -coverprofile=coverage.out -covermode=atomic ./...

      - name: codecov.io coverage
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
